[1m============================= test session starts ==============================[0m
platform linux -- Python 3.10.12, pytest-6.2.5, py-1.10.0, pluggy-0.13.0
cachedir: /workspace/build/task01/.pytest_cache
rootdir: /workspace/src/task01
plugins: ament-copyright-0.14.4, ament-pep257-0.14.4, launch-testing-ros-0.24.1, ament-lint-0.14.4, launch-testing-2.0.4, ament-xmllint-0.14.4, ament-flake8-0.14.4, colcon-core-0.17.0
[1mcollecting ... [0m[1m
collected 3 items                                                              [0m

test/test_copyright.py [33ms[0m[32m                                                 [ 33%][0m
test/test_flake8.py [31mF[0m[31m                                                    [ 66%][0m
test/test_pep257.py [32m.[0m[31m                                                    [100%][0m

=================================== FAILURES ===================================
[31m[1m_________________________________ test_flake8 __________________________________[0m
[1m[31mtest/test_flake8.py[0m:23: in test_flake8
    [94massert[39;49;00m rc == [94m0[39;49;00m, \
[1m[31mE   AssertionError: Found 1 code style errors / warnings:[0m
[1m[31mE     ./setup.py:1:1: F401 'setuptools.find_packages' imported but unused[0m
[1m[31mE   assert 1 == 0[0m
----------------------------- Captured stdout call -----------------------------

./setup.py:1:1: F401 'setuptools.find_packages' imported but unused
from setuptools import find_packages, setup
^

1     F401 'setuptools.find_packages' imported but unused

6 files checked
1 errors

'F'-type errors: 1

Checked files:

* ./setup.py
* ./task01/__init__.py
* ./task01/receiver.py
* ./test/test_pep257.py
* ./test/test_flake8.py
* ./test/test_copyright.py
----------------------------- Captured stderr call -----------------------------
option --max-complexity: please update from optparse string `type=` to argparse callable `type=` -- this will be an error in the future
------------ generated xml file: /workspace/build/task01/pytest.xml ------------
=========================== short test summary info ============================
FAILED test/test_flake8.py::test_flake8 - AssertionError: Found 1 code style ...
[31m============== [31m[1m1 failed[0m, [32m1 passed[0m, [33m1 skipped[0m, [33m2 warnings[0m[31m in 0.38s[0m[31m ==============[0m
